CREATE TABLE IF NOT EXISTS crmpro_v2_whatsapp_test.whatsapp_automation_queue (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    automation_id INT NOT NULL,
    event_key VARCHAR(191) NOT NULL UNIQUE,
    trigger_event VARCHAR(100) NOT NULL,
    lead_type ENUM('DIRECT','BOT') NOT NULL,
    lead_table VARCHAR(100) NOT NULL,
    lead_id INT NOT NULL,
    telecaller_id INT NULL,
    phone_number VARCHAR(25) NOT NULL,
    normalized_number VARCHAR(10) NOT NULL,
    scheduled_at DATETIME NOT NULL,
    service_window_expires_at DATETIME NULL,
    variables_json JSON NULL,
    automation_name_snapshot VARCHAR(255),
    message_type_snapshot VARCHAR(30),
    caption_snapshot TEXT,
    media_url_snapshot TEXT,
    file_name_snapshot VARCHAR(255),
    status ENUM(
        'PENDING',
        'PROCESSING',
        'SENT',
        'FAILED',
        'SKIPPED',
        'WINDOW_EXPIRED',
        'UNSUPPORTED_MEDIA'
    ) NOT NULL DEFAULT 'PENDING',
    retry_count INT NOT NULL DEFAULT 0,
    next_retry_at DATETIME NULL,
    whatsapp_message_id VARCHAR(255) NULL,
    error_message TEXT NULL,
    sent_at DATETIME NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_status_scheduled (status, scheduled_at),
    INDEX idx_automation (automation_id),
    INDEX idx_lead (lead_type, lead_id),
    INDEX idx_number (normalized_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
